tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "wtfutil/wtfutil"

brew "ansible"
brew "app-engine-python"
brew "awscli"
brew "boost"
brew "glib"
brew "fdupes"
brew "ffmpeg"
brew "fortune"
brew "gnutls"
brew "gnupg"
brew "go"
brew "protobuf"
brew "grpc"
brew "htop"
brew "neovim"

brew "hugo"
brew "iat"
brew "jenv"
brew "jhead"
brew "lua"
brew "luarocks"
brew "mkvtoolnix"
brew "mosh"
brew "ncdu"
brew "nmap"
brew "node"
brew "pkg-config"
brew "pv"
brew "ruby"
brew "sqlcipher"
brew "teleconsole"
brew "unrar"
brew "wget"
brew "wtfutil"
brew "lolcat"
brew "figlet"

tap "chrokh/tap"

cask "appcleaner"
cask "flux"
cask "google-cloud-sdk"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "java"
cask "macvim"
cask "mailmate"
cask "signal"
cask "skype"
cask "spotify"
cask "telegram"
cask "twitch"
cask "visual-studio-code"
cask "vlc"

mas "Contacts+", id: 1094748271
mas "Day One", id: 1055511498
mas "GrandPerspective", id: 1111570163
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pixelmator", id: 407963104
mas "Simplenote", id: 692867256
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "Tailscale", id: 1475387142
mas "Todoist", id: 585829637
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
