
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ansible"
brew "awscli"
brew "boost"
brew "exiftool"
brew "fdupes"
brew "ffmpeg"
brew "figlet"
brew "fish"
brew "fish"
brew "fortune"
brew "glib"
brew "gnupg"
brew "gnutls"
brew "go"
brew "grpc"
brew "htop"
brew "hugo"
brew "iat"
brew "jenv"
brew "jhead"
brew "lolcat"
brew "lua"
brew "luarocks"
brew "mkvtoolnix"
brew "mosh"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node"
brew "pkg-config"
brew "protobuf"
brew "pv"
brew "ruby"
brew "speedtest-cli"
brew "sqlcipher"
brew "wget"
brew "wtfutil"

cask "1password"
cask "aerial"
cask "appcleaner"
cask "arc"
cask "cron"
cask "discord"
cask "figma"
cask "google-cloud-sdk"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "hammerspoon"
cask "iterm2"
cask "ledger-live"
cask "logseq"
cask "lunar"
cask "macvim"
cask "maestral"
cask "mailmate"
cask "microsoft-teams"
cask "mimestream"
cask "netnewswire"
cask "notion"
cask "numi"
cask "nvidia-geforce-now"
cask "pitch"
cask "plexamp"
cask "protonmail-bridge"
cask "rapidapi"
cask "signal"
cask "spotify"
cask "tailscale"
cask "telegram"
cask "trezor-suite"
cask "twitch"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# mas "Contacts+", id: 1094748271
# mas "Crypto Pro", id: 980888073
# mas "Soulver", id: 413965349
# mas "TweetDeck", id: 485812721
# mas "Zerion", id: 1456732565
mas "Apple Configurator", id: 1037126344
mas "Day One", id: 1055511498
mas "Drafts", id: 1435957248
mas "GrandPerspective", id: 1111570163
mas "Keynote", id: 409183694
mas "Line", id: 539883307
mas "Mastonaut", id: 1450757574
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pixelmator Pro", id: 407963104
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Todoist", id: 585829637
mas "UTM", id: 1538878817
mas "Xcode", id: 497799835

