#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  echo "OMG OSX"
  
  # if we have fonts get them to the greek
  if [ -d "$~/.config/fonts/" ]; then
     cp ~/.config/fonts/*.ttf /Library/Fonts/
  fi
  
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh
  fi

  # look for a brewfile and bootstrap brew
  if [ -f "$HOME/.config/brewfile/Brewfile" ]; then
    brew bundle --file "$HOME/.config/brewfile/Brewfile"
  fi

  # if we have fish make it the default shell
  if command -v fish >/dev/null 2>&1; then
    echo "Setting Fish as default shell"
    echo `which fish` | sudo tee -a /etc/shells
    chsh -s `which fish`
  fi


elif [ "$system_type" = "Linux" ]; then

   echo "OMG Linux"
   sudo apt install fish kitty yadm figlet lolcat variety fortune remmina
fi

