#!/bin/bash

system_type=$(uname -s)
arch_type=$(uname -m)

if [ "$system_type" = "Darwin" ]; then
  echo "OMG OSX"

  if [ "$arch_type" = "arm64" ]; then
    echo "The newest in new"

    if ! command -v brew >/dev/null 2>&1; then
      echo "Installing arm homebrew"
      sudo mkdir -p /opt/homebrew
      sudo chown -R $(whoami):staff /opt/homebrew
      cd /opt
      curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
    fi

    # look for a brewfile and bootstrap brew
    if [ -f "$HOME/.config/brewfile/Brewfile" ]; then
      brew bundle --file "$HOME/.config/brewfile/Brewfile.arm64"
    fi

    # if we have fish make it the default shell
    if command -v fish >/dev/null 2>&1; then
      echo "Setting Fish as default shell"
      echo `which fish` | sudo tee -a /etc/shells
      chsh -s `which fish`
    fi

  else
    echo "this"
    # if we have fonts get them to the greek
    if [ -d "$~/.config/fonts/" ]; then
      cp ~/.config/fonts/*.ttf /Library/Fonts/
    fi
    
    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
      echo "Installing homebrew"
      curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh
    fi

    # look for a brewfile and bootstrap brew
    if [ -f "$HOME/.config/brewfile/Brewfile" ]; then
      brew bundle --file "$HOME/.config/brewfile/Brewfile"
    fi

    # if we have fish make it the default shell
    if command -v fish >/dev/null 2>&1; then
      echo "Setting Fish as default shell"
      echo `which fish` | sudo tee -a /etc/shells
      chsh -s `which fish`
    fi
  fi
  


elif [ "$system_type" = "Linux" ]; then

   echo "OMG Linux"
   sudo apt install fish  yadm figlet lolcat  fortune npm speedtest-cli bsdgames -y
   
    if ! xset q &>/dev/null; then
        echo "No X server at \$DISPLAY [$DISPLAY]" >&2
        exit 1
    elif xset q &>/dev/null; then
        npm install variety kitty remmina -y
        #keybase
        if [ ! -f /etc/apt/sources.list.d/keybase.list ]; then
        curl https://keybase.io/docs/server_security/code_signing_key.asc | gpg --dearmor > keybase.gpg
        sudo mv keybase.gpg /etc/apt/trusted.gpg.d/keybase.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://prerelease.keybase.io/deb stable main" > /etc/apt/sources.list.d/keybase.list'
        sudo apt-get update
        fi
  
        sudo apt-get install keybase -y # or code-insiders

        #CODE
        if [ ! -f /etc/apt/sources.list.d/vscode.list ]; then
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
            sudo apt-get update
        fi

        sudo apt-get install code -y # or code-insiders
    fi
   
   

fi

