# ABOUTME: Hyprpaper wallpaper config
# ABOUTME: Sets desktop background image

preload = /home/harper/Pictures/variety-copied-wallpaper-97b6bfb4b03443a77056a1d5255d7f2a.jpg
wallpaper = ,/home/harper/Pictures/variety-copied-wallpaper-97b6bfb4b03443a77056a1d5255d7f2a.jpg
