wtf:
  grid:
    columns: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
    rows: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  colors:
    background: "black"
    border:
      focusable: "cyan"
      focused: "yellow"
      normal: "white"
    checked: "green"
    highlight:
      fore: "black"
      back: "cyan"
    rows:
      even: "black"
      odd: "white"
  refreshInterval: 1
  mods:
    # === TOP ROW: Time & System Info ===
    clocks:
      enabled: true
      colors:
        rows:
          even: "cyan"
          odd: "white"
      sort: "chronological"
      locations:
        TKO: "Asia/Tokyo"
        ORD: "America/Chicago"
        NYC: "America/New_York"
        SFO: "America/Los_Angeles"
        LHR: "Europe/London"
        UTC: "UTC"
      position:
        top: 0
        left: 0
        height: 2
        width: 3
      timeFormat: "3:04 PM"
      refreshInterval: 30s

    system_info:
      type: "cmdrunner"
      args: []
      cmd: "uname -s && uptime | awk '{print \"Load: \" $(NF-2) \" \" $(NF-1) \" \" $NF}' && df -h / | tail -1 | awk '{print \"Disk: \" $4 \" free\"}'"
      enabled: true
      title: "💻 System"
      position:
        top: 0
        left: 3
        height: 2
        width: 2
      refreshInterval: 60

    battery:
      type: power
      title: "🔋 Power"
      enabled: true
      position:
        top: 0
        left: 5
        height: 2
        width: 2
      refreshInterval: 30s

    # === SECOND ROW: Network & Weather ===
    ipinfo:
      enabled: true
      title: "🌐 Network"
      position:
        top: 2
        left: 0
        height: 2
        width: 3
      refreshInterval: 300s

    prettyweather:
      enabled: true
      title: "🌤️ Weather"
      city: "Chicago"
      refreshInterval: 10m
      unit: "m"
      view: 0
      language: "en"
      position:
        top: 2
        left: 3
        height: 2
        width: 4

    # === THIRD ROW: Development & Git ===
    git:
      enabled: true
      commitCount: 5
      commitFormat: "[%h] %s"
      dateFormat: "Jan 2 15:04"
      excludes: ["vendor/", "node_modules/"]
      remotes: ["origin"]
      repositories:
        "/Users/harper/Public/src/personal/dotfiles":
          name: "dotfiles"
        "/Users/harper/Public/src/personal":
          name: "personal"
      title: "📁 Git Status"
      position:
        top: 4
        left: 0
        height: 3
        width: 4
      refreshInterval: 60

    docker:
      enabled: true
      labelColor: "lightblue"
      showStatistics: true
      title: "🐳 Docker"
      position:
        top: 4
        left: 4
        height: 3
        width: 3
      refreshInterval: 30

    # === RIGHT COLUMN: News & Information ===
    hackernews:
      enabled: true
      numberOfStories: 12
      title: "📰 Hacker News"
      position:
        top: 0
        left: 7
        height: 4
        width: 3
      refreshInterval: 10m

    reddit:
      enabled: true
      numberOfStories: 8
      subreddit: "programming"
      title: "🤖 r/programming"
      position:
        top: 4
        left: 7
        height: 3
        width: 3
      refreshInterval: 15m

    # === BOTTOM ROW: System Monitoring ===
    cpu_usage:
      type: "cmdrunner"
      args: []
      cmd: "top -l 1 | grep 'CPU usage' | sed 's/CPU usage: /CPU: /' && echo 'Memory:' && vm_stat | grep -E 'Pages (free|active|wired)' | awk '{printf \"%s %s\\n\", $1 $2, $3}' | head -3"
      enabled: true
      title: "📊 Resources"
      position:
        top: 7
        left: 0
        height: 3
        width: 3
      refreshInterval: 5s

    processes:
      type: "cmdrunner"
      args: []
      cmd: "ps aux | sort -nr -k 3 | head -6 | awk '{print $11 \" (\" $3 \"%)\"}'"
      enabled: true
      title: "🔥 Top CPU"
      position:
        top: 7
        left: 3
        height: 3
        width: 2
      refreshInterval: 10s

    network_traffic:
      type: "cmdrunner"
      args: []
      cmd: "ifconfig | grep -A 1 'en0:' | grep 'inet ' | awk '{print \"WiFi: \" $2}' && netstat -i | grep en0 | awk '{print \"Packets: \" $5 \"/\" $7}'"
      enabled: true
      title: "📡 Network"
      position:
        top: 7
        left: 5
        height: 3
        width: 2
      refreshInterval: 30s

    shortcuts:
      type: "textfile"
      filePaths: ["/Users/harper/.config/wtf/shortcuts.txt"]
      enabled: true
      title: "⌨️ Shortcuts"
      position:
        top: 7
        left: 7
        height: 3
        width: 3
      refreshInterval: 300s
